10 REM @HI@AML@OJ@AL@OBCEL@O@CAL@NNCFL@NLCBL@NDCGL@NBCCLGOOL@ND@GL@MOCO
11 REM LHML@FLHMK@ALHMGCFLHMACBLHLOCELHLICALHLGCGLHLACCLHKOLDOFCBLDGKCF
12 REM LDGOCGLDJDCCCO@M@JDKFIGDFBGEFGBKB@CNB@@@LD@OCGLDGFCCCOD@NDEBILEK
13 REM LDOFCBLDGKCFLDGOCGLDJDCCCO@M@JE@DCB@B@B@E@EDEBCAB@E@EDEBCBB@DADC
14 REM B@DEEHB@ECED@M@J@@LDGKCELDOGCALDGNCGLDOLCCLE@ACOLE@ACOLG@BLE@ACO
15 REM LE@ACOLG@BLE@ACOLE@ACOLE@ACOLE@ACOLE@ACOLDGLCGLDCICCCOD@NDDNIL@M
16 REM LDB@CBLDAACFLD@ICGLDFOCCCOD@NDCOIH@GLDGMCGLDHDCCCOLDGOCGLDJDCCCO
17 REM @M@JDKDBBKB@FCFOFMFMFAFNFDGCCJB@DDFIGCG@FLFAGIBLB@DGFOBLB@DLFIGC
18 REM GDBLB@DMFOFDFIFFGIBLB@DNFIFBFLBLB@EDGIG@FEBLB@EBFEFGGCBLB@CO@M@J
19 REM EBFEFGGCB@E@DCCMCGDBDFCGBOCHBLB@E@CACMCGDBDFCIBODABLB@E@CBCMCGDB
20 REM DFDBBODCBLB@DACMCGDBDFDDBLB@DECMCGDBDFDEBLB@ECCMCGDBDFDF@M@JECFE
21 REM GDB@FBGBFKG@GDB@GGFIGDFHB@FAFNB@EHE@E@DCB@E@DCB@BHBDCCDFBI@@LDGL
22 REM CGLDCICCCOD@NDDGILCBLDGNCGLDIHCCCOND@MIH@GLDGNCGLDGHCCCOLF@ACELF
23 REM @ACALDGKCGLDOGCCCELO@ACALO@ALDGLCGLD@BCCCOLDGLCGLDCICCCOD@NDEDIH
24 REM @ID@NDDMILGCLD@@I@@BLD@ALNOOLDGNCGLDIHCCCOND@MIH@GLDGNCGLDGHCCCO
25 REM LF@ACELF@ACA@FMDA@IL@GLDGLCGLDCICCCOLD@OCGLDKICCLD@MCOLD@JCOCE@A
26 REM D@CELDGNCGLDOLCCD@COCA@AD@CAD@COLE@ACOLB@@ILLOLD@OCGLDGFCCCOND@M
27 REM IHLDNDAEIHHOLDGNCGLDIDCCCOND@MILDHLF@ALF@ALIOOI@JMD@NDDDILAHLDGN
28 REM CGLDIHCCCOND@MILC@LF@ACELF@ACALDGOCGLDD@CCCOD@NDDLILANLDOFCBLDGK
29 REM CFLDGNCGLDIHCCCOND@MIL@MLF@ACELF@ACALDGOCGLDL@CCCOLD@OCGLDKICCLD
30 REM @JCOLDCOCOLD@MCOLD@JCOLD@MCOLDGLCGLDCICCCOLD@AI@@BLD@@LJOKLDGFCC
31 REM LNOMLD@OCGLNOOLBOOIL@ACOLD@@LJ@CLJ@BD@@COLCJID@O@COLOFIDAILF@ACG
32 REM LF@ACCD@COI@MB@COL@MIDOA@COLOJID@BI@NJ@BOD@JLJOOLD@DLJON@BLB@COB
33 REM @CLJ@CLB@BOB@BLJ@BKJONILNO@BLB@COBOOLJ@CCOI@KKLNOOLDB@I@@DLNOOLD
34 REM @@LNOOLDKICCLNOOLD@OCGLNOOLD@BLNOOLB@DALALALAL@BODOFID@DODCJI@@B
35 REM ODD@COKJ@@IH@FLB@DMD@OI@NJLB@CIH@ACOLB@ACGLB@BCCLF@DLF@ACOI@KHI@
36 REM KLLDOFCBLDGKCFLDA@LJOGLDA@LJOHLD@OCGLDKICCLD@MCOLD@JCOCE@AD@CELD
37 REM GNCGLDOLCCD@COCA@AD@CAD@COLE@ACOKJOHILOILD@OCGLDKICCLDB@COLEO@LD
38 REM A@LJOHLE@AID@BLDBNMDGO@COLB@ID@BLD@N@BODB@COKJOHILNIKJOGILJMLDGL
39 REM CGLDCICCCOCCCACGCELE@ALD@OCGLDKICCLE@AIH@CCOI@OILEOOCACCCECGCOI@
40 REM NDLDOFCBLDGKCFLDA@LJOGLD@OCGLDKICCLD@MCOLD@JCOCE@AD@CELDGNCGLDOL
41 REM CCD@COCA@AD@CAD@COLE@ACOLAOOID@CLE@ACOKJOGILMDLDGLCGLDCICCCO@@@@
60 PR"KitbugPlus loader for pic32K - LINK#7C00 when finished..."
70 PR"Its slow, 3 mins, but with NVRAM only needs to be done once."
80 PR"See doc for Kitbug+ details. This ver KBPLUS-01-01-25. PE1GOO"
90 IF PAGE<>2 PR"Must be run from PAGE 2":END
100 M=#7C00
120 FOR L=0 TO 31
130 FOR B=0 TO 62 STEP 2
140 A=#200A + B + L*73
150 X=@A AND 15:Y=@(A+1) AND 15:Z=16*X+Y:@M=Z:M=M+1
180 NEXT B:NEXT L
