10 REM @HI@AML@OJ@AL@OBCEL@O@CAL@NNCFL@NLCBL@NDCGL@NBCCLGOOL@ND@GL@MOCO
11 REM LHML@FLHMK@ALHMGCFLHMACBLHLOCELHLICALHLGCGLHLACCLHKOLDOFCBLDGJCF
12 REM LDGNCGLDJJCCCO@M@JDKFIGDFBGEFGBKB@CNB@@@LD@OCGLDGFCCCOD@NDEBILEK
13 REM LDOFCBLDGJCFLDGNCGLDJJCCCO@M@JE@DCB@B@B@E@EDEBCAB@E@EDEBCBB@DADC
14 REM B@DEEHB@ECED@M@J@@LDGJCELDOGCALDGMCGLDOLCCLE@ACOLE@ACOLG@BLE@ACO
15 REM LE@ACOLG@BLE@ACOLE@ACOLE@ACOLE@ACOLE@ACOLDGKCGLDCICCCOD@NDDNIL@M
16 REM LDB@CBLDAACFLD@ICGLDFOCCCOD@NDCOIH@GLDGLCGLDHDCCCOLDGNCGLDJJCCCO
17 REM @M@JDKDBBKB@FCFOFMFMFAFNFDGCCJB@DDFIGCG@FLFAGIBLB@DGFOBLB@DLFIGC
18 REM GDBLB@DMFOFDFIFFGIBLB@DNFIFBFLBLB@EDGIG@FEBLB@EBFEFGGCBLB@CO@M@J
19 REM EBFEFGGCB@E@DCCMCGDBDFCGBOCHBLB@E@CACMCGDBDFCIBODABLB@E@CBCMCGDB
20 REM DFDBBODCBLB@DACMCGDBDFDDBLB@DECMCGDBDFDEBLB@ECCMCGDBDFDF@M@JECFE
21 REM GDB@FBGBFKG@GDB@GGFIGDFHB@FAFNB@EHE@E@DCB@E@DCB@BHBDCCDFBI@@LDGK
22 REM CGLDCICCCOD@NDDGILCBLDGMCGLDIHCCCOND@MIH@GLDGMCGLDGHCCCOLF@ACELF
23 REM @ACALDGJCGLDOGCCCELO@ACALO@ALDGKCGLD@BCCCOLDGKCGLDCICCCOD@NDEDIH
24 REM @ID@NDDMILGCLD@@I@@BLD@ALNOOLDGMCGLDIHCCCOND@MIH@GLDGMCGLDGHCCCO
25 REM LF@ACELF@ACA@FMDA@IL@GLDGKCGLDCICCCOLD@OCGLDKICCLD@MCOLD@JCOCE@A
26 REM D@CELDGMCGLDOLCCD@COCA@AD@CAD@COLE@ACOLB@@ILLOLD@OCGLDGFCCCOND@M
27 REM IHLDNDAEIHHOLDGMCGLDIDCCCOND@MILDHLF@ALF@ALIOOI@JMD@NDDDILAHLDGM
28 REM CGLDIHCCCOND@MILC@LF@ACELF@ACALDGNCGLDD@CCCOD@NDDLILANLDOFCBLDGJ
29 REM CFLDGMCGLDIHCCCOND@MIL@MLF@ACELF@ACALDGNCGLDLFCCCOLD@OCGLDKICCLD
30 REM @JCOLDCOCOLD@MCOLD@JCOLD@MCOLDGKCGLDCICCCOLD@AI@@BLD@@LJOKLDGFCC
31 REM LNOMLD@OCGLNOOLBOOIL@ACOLD@@LJ@CLJ@BD@@COLCJID@O@COLOFIDAILF@ACG
32 REM LF@ACCD@COI@MB@COL@MIDOA@COLOJID@BI@NJ@BOD@JLJOOLD@DLJON@BLB@COB
33 REM @CLJ@CLB@BOB@BLJ@BKJONILNO@BLB@COBOOLJ@CCOI@KKLNOOLDB@I@@DLNOOLD
34 REM @@LNOOLDKICCLNOOLD@OCGLNOOLD@BLNOOLB@DALALALAL@BODOFID@DODCJI@@B
35 REM ODD@COKJ@@IH@FLB@DMD@OI@NJLB@CIH@ACOLB@ACGLB@BCCLF@DLF@ACOI@KHI@
36 REM KLLDOFCBLDGJCFLDA@LJOGLDA@LJOHLD@OCGLDKICCLD@MCOLD@JCOCE@AD@CELD
37 REM GMCGLDOLCCD@COCA@AD@CAD@COLE@ACOKJOHILOILD@OCGLDKICCLDB@COLEO@LD
38 REM A@LJOHLE@AID@BLDBNMDGONDGOIHOHNDGO@COLB@ID@BLD@N@BODB@COKJOHILNC
39 REM KJOGILJGLDGKCGLDCICCCOCCCACGCELE@ALD@OCGLDKICCLE@AIH@CCOI@OILEOO
40 REM CACCCECGCOI@NDLDOFCBLDGJCFLDA@LJOGLD@OCGLDKICCLD@MCOLD@JCOCE@AD@
41 REM CELDGMCGLDOLCCD@COCA@AD@CAD@COLE@ACOLAOOID@CLE@ACOKJOGILMDLDGKCG
42 REM LDCICCCO@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@@
60 PR"KitbugPlus loader for pic32K - LINK#7B00 when finished..."
70 PR"Its slow, 3 mins, but with NVRAM only needs to be done once."
80 PR"See doc for Kitbug+ details. This ver KBPLUS-17-01-25. PE1GOO"
90 IF PAGE<>2 PR"Must be run from PAGE 2":END
100 M=#7B00
120 FOR L=0 TO 32
130 FOR B=0 TO 62 STEP 2
140 A=#200A + B + L*73
150 X=@A AND 15:Y=@(A+1) AND 15:Z=16*X+Y:@M=Z:M=M+1
180 NEXT B:NEXT L
